name: Build CI

on:
  push:
    branches: acc_initial
  pull_request:
    branches: acc_initial

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: build ACC
      run: gcc -o ACC ACC\ Algorithm/AlgorithMain.c
      
    - name: Upload Executables
      uses: actions/upload-artifact@v4
      with:
        name: Executable
        path: ./ACC
